CREATE TABLE LOCATION_LOCATION_MAPPING (
  ID                 SERIAL PRIMARY KEY,
  LOCATION_ID        BIGINT,
  PARENT_LOCATION_ID BIGINT,
  VERSION            INTEGER,
  AUDIT_ID           BIGINT,
  UUID_REF           VARCHAR(255)
);

INSERT INTO LOCATION_LOCATION_MAPPING (UUID_REF, LOCATION_ID, PARENT_LOCATION_ID, VERSION)
SELECT UUID, ID, PARENT_ID, VERSION
FROM ADDRESS_LEVEL
WHERE PARENT_ID IS NOT NULL;

INSERT INTO AUDIT (UUID, CREATED_BY_ID, LAST_MODIFIED_BY_ID, CREATED_DATE_TIME, LAST_MODIFIED_DATE_TIME)
SELECT UUID, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM ADDRESS_LEVEL
WHERE PARENT_ID IS NOT NULL;

UPDATE LOCATION_LOCATION_MAPPING
SET AUDIT_ID = (SELECT ID
                FROM AUDIT
                WHERE AUDIT.UUID = LOCATION_LOCATION_MAPPING.UUID_REF);

ALTER TABLE ONLY LOCATION_LOCATION_MAPPING
  ADD CONSTRAINT LOCATION_LOCATION_MAPPING_LOCATION FOREIGN KEY (LOCATION_ID) REFERENCES ADDRESS_LEVEL (ID),
  ADD CONSTRAINT LOCATION_LOCATION_MAPPING_PARENT_LOCATION FOREIGN KEY (PARENT_LOCATION_ID) REFERENCES ADDRESS_LEVEL (ID),
  ADD CONSTRAINT LOCATION_LOCATION_MAPPING_AUDIT FOREIGN KEY (AUDIT_ID) REFERENCES AUDIT (ID),
  ALTER COLUMN VERSION SET NOT NULL,
  DROP COLUMN UUID_REF;
